# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  build_and_publish:
    parameters:
      image:
        description: Machine image name
        type: string
      resource_class:
        description: Resource class of machine
        type: string
      image_name:
        description: Named to be used for image in Docker Registry (don't include the tag)
        type: string
      platform:
        description: Platform for image
        type: string
      registry:
        description: Docker Registry to push image to
        type: string
      namespace:
        description: Docker Registry to push image to
        type: string
    machine:
      image: << parameters.image >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run:
          name: Docker Build
          command: |
            make -C << parameters.image_name >> build/<< parameters.platform >>
      - when:
          condition: << pipeline.git.branch >> == "initial-setup"
          steps:
            - run:
                name: Docker Push
                command: |
                  printf "token --> %s\n" "$GHCR_TOKEN"
                  printf "registry --> %s\n" "<< parameters.registry >>"
                  printf "username --> %s\n" "$GHCR_USER"
                  printf "names --> %s\n" "<< parameters.namespace >>"
                  # make -C << parameters.image_name >> push/<< parameters.platform >> \
                  #   token="$GHCR_TOKEN" \
                  #   registry='<< parameters.registry >>' \
                  #   username="$GHCR_USER"
                  #   namespace='<< parameters.namespace >>'

workflows:
  main:
    jobs:
      - build_and_publish:
          name: Build and Publish linux/arm64
          image: ubuntu-2204:2023.04.2
          resource_class: arm.medium
          image_name: amazonlinux
          platform: linux/arm64
          context: protagona
          registry: ghcr.io
          namespace: protagona

      - build_and_publish:
          name: Build and Publish linux/amd64
          image: ubuntu-2204:2023.04.2
          resource_class: medium
          image_name: amazonlinux
          platform: linux/amd64
          context: cloudmagick
          registry: ghcr.io
          namespace: protagona
