# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  build:
    machine:
      image: << parameters.image >>
    parameters:
      image:
        description: Machine image name
        type: string
      resource_class:
        description: Resource class of machine
        type: string
      image_name:
        description: Named to be used for image in Docker Registry (don't include the tag)
        type: string
      platform:
        description: Platform for image
        type: string
      registry:
        description: Docker Registry to push image to
        type: string
      namespace:
        description: Docker Registry to push image to
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run:
          command: |
            echo "$GHCR_TOKEN" | docker login -u "$GHCR_USER" --password-stdin ghcr.io
      - run:
          name: Docker Build
          command: |
            make -C << parameters.image_name >> build/<< parameters.platform >>
      - run:
          name: Docker Publish
          command: |
            make -C << parameters.image_name >> push/<< parameters.platform >> \
              token="$GHCR_TOKEN" \
              registry='<< parameters.registry >>' \
              username="$GHCR_USER" \
              namespace='<< parameters.namespace >>'

  publish:
    machine:
      image: << parameters.image >>
    parameters:
      image:
        description: Machine image name
        type: string
      resource_class:
        description: Resource class of machine
        type: string
      image_name:
        description: Named to be used for image in Docker Registry (don't include the tag)
        type: string
      registry:
        description: Docker Registry to push image to
        type: string
      namespace:
        description: Docker Registry to push image to
        type: string
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run:
          name: Docker Create Manifest
          command: |
            make -C << parameters.image_name >> push/manifest \
              token="$GHCR_TOKEN" \
              registry='<< parameters.registry >>' \
              username="$GHCR_USER" \
              namespace='<< parameters.namespace >>'

workflows:
  main:
    jobs:
      - build:
          name: Build << matrix.image_name >> linux/amd64
          image: ubuntu-2204:2023.04.2
          context: protagona
          resource_class: large
          platform: linux/amd64
          namespace: protagona
          registry: ghcr.io
          matrix:
            parameters:
              image_name:
                - cicd-test
                - amazonlinux
                - fedora

      - build:
          name: "Build << matrix.image_name >> linux/arm64"
          image: ubuntu-2204:2023.04.2
          context: protagona
          resource_class: arm.large
          platform: linux/arm64
          namespace: protagona
          registry: ghcr.io
          matrix:
            parameters:
              image_name:
                - cicd-test
                - amazonlinux
                - fedora

      - publish:
          requires:
            - Build cicd-test linux/amd64
            - Build cicd-test linux/arm64
          name: Publish cicd-test multi-platform manifest
          image: ubuntu-2204:2023.04.2
          context: protagona
          namespace: protagona
          registry: ghcr.io
          resource_class: medium
          image_name: cicd-test

      - publish:
          requires:
            - Build amazonlinux linux/amd64
            - Build amazonlinux linux/arm64
          name: Publish amazonlinux multi-platform manifest
          image: ubuntu-2204:2023.04.2
          context: protagona
          namespace: protagona
          registry: ghcr.io
          resource_class: medium
          image_name: amazonlinux

      - publish:
          requires:
            - Build fedora linux/amd64
            - Build fedora linux/arm64
          name: Publish fedora multi-platform manifest
          image: ubuntu-2204:2023.04.2
          context: protagona
          namespace: protagona
          registry: ghcr.io
          resource_class: medium
          image_name: fedora
